#!/bin/ksh

if [[ $# -eq 0 ]]; then
  echo "Usage: $(basename $0) [-n] [firefoxcookiefile.sqlite]"
  echo "If given the -n flag, this script will try to guess"
  echo "where your cookies file is instead of printing this help"
  exit 1
fi

if [[ $1 = "-n" ]]; then
  SQLFILE="$(find $HOME/.mozilla/firefox -name cookies.sqlite)"
else
  SQLFILE="$1"
fi
SQL=sqlite3

echo 'SELECT * FROM moz_cookies;' |"$SQL" "$SQLFILE"
